services:
  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - o-n-logistics
    environment:
      SPRING_PROFILES_ACTIVE: dev
    platform: linux/amd64

  # 다른 서비스들도 여기에 추가

networks:
  o-n-logistics:
    driver: bridge