spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 서비스 디스커버리로 동적 라우트 생성
      auth_global_filter:
        login_url: /api/v1/auth/login
        signup_url: /api/v1/auth/signup
        base_url: http://localhost:18081
        validate_endpoint: /api/v1/auth/validate
      routes:
        - id: auth-service # 인증 서비스
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        - id: user-service # 사용자 서비스
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**

        - id: delivery-manager-service # 배송 담당자 서비스
          uri: lb://delivery-manager-service
          predicates:
            - Path=/api/v1/delivery-managers/**

        - id: order-service # 주문 서비스
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**

        - id: delivery-service # 배송 서비스
          uri: lb://delivery-service
          predicates:
            - Path=/api/v1/delivery/**

        - id: company-service # 업체 서비스
          uri: lb://company-service
          predicates:
            - Path=/api/v1/company/**

        - id: product-service # 상품 서비스
          uri: lb://product-service
          predicates:
            - Path=/api/v1/product/**

        - id: hub-service # 허브 서비스
          uri: lb://hub-service
          predicates:
            - Path=/api/v1/hubs/**

        - id: hub-transit-route-service # 허브 간 이동 정보 서비스
          uri: lb://hub-transit-route-service
          predicates:
            - Path=/api/v1/hub-transit/route/**

        - id: slack-service # 슬랙 서비스
          uri: lb://slack-service
          predicates:
            - Path=/api/v1/slack/**

        - id: ai-service # AI 서비스
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**

        - id: map-service # 지도 서비스
          uri: lb://map-service
          predicates:
            - Path=/api/v1/maps/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
