version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: onlogistics
      POSTGRES_PASSWORD: onlogistics
      POSTGRES_DB: onlogistics
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - o-n-logistics

volumes:
  postgres-data:
  redis-data:

networks:
  o-n-logistics:
    driver: bridge