spring:
  datasource:
    url: ENC(+RN5170xnJ0QU1FdEXV4MnCpm52yivr2NwnhV7tdDEDhUD6DLfBjGEfpLz3EKQOCbYZ4mGyMJ4k=)
    username: ENC(327eellHMCu8HWWlCQQZeg==)
    password: ENC(FEiIBGvilAmYxv/xuYY35cWZXF1hIj+b)
  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        format_sql: true
        highlight_sql: true
        use_sql_comments: true
    #    show-sql: true
    open-in-view: false

decorator:
  datasource:
    p6spy:
      enable-logging: true